services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: moviestrack
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
  api:
    image: ghcr.io/panosdim/movies-track-api
    container_name: movies-track-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: production
    ports:
      - '8080:8080'
    depends_on:
      - postgres

