services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: moviestrack
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
