INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (11, 1100988, '/5SyBozBOc2PGH6QIIlMDpfOCB5b.jpg', 0, '28 Years Later', 'panosdim@gmail.com', false);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (21, 575265, '/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg', 0, 'Mission: Impossible - The Final Reckoning', 'panosdim@gmail.com', false);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (25, 1233575, '/yCVJ8joYTzf9tCby9o9H7zhEVG8.jpg', 0, 'Black Bag', 'panosdim@gmail.com', false);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (26, 1234821, '/8BZ6oGDE336qFshFC44WxZtosBX.jpg', 0, 'Jurassic World Rebirth', 'panosdim@gmail.com', false);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (28, 696506, '/lrCcovGRcuv8Z1v3ae1ZH5Ird05.jpg', 0, 'Mickey 17', 'panosdim@gmail.com', false);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (31, 1233413, '/yqsCU5XOP2mkbFamzAqbqntmfav.jpg', 0, 'Sinners', 'panosdim@gmail.com', false);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (32, 870028, '/4rxr2grcBfxwH4penSxndcPwyDp.jpg', 0, 'The Accountant 2', 'panosdim@gmail.com', false);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (1, 533535, '/uxBHXaoOvAwy4NpPpP7nNx2rXYQ.jpg', 3, 'Deadpool & Wolverine', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (2, 519182, '/aun2IpLDx2E08hYj8xnAEUEFLlo.jpg', 4, 'Despicable Me 4', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (3, 558449, '/f54mzACTFdiAxnQ30BK4GjrKzyn.jpg', 4, 'Gladiator II', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (5, 945961, '/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg', 3, 'Alien: Romulus', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (6, 1022789, '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg', 4, 'Inside Out 2', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (7, 1011985, '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg', 4, 'Kung Fu Panda 4', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (8, 653346, '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg', 4, 'Kingdom of the Planet of the Apes', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (9, 573435, '/oGythE98MYleE6mZlGs5oBGkux1.jpg', 3, 'Bad Boys: Ride or Die', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (10, 762441, '/hU42CRk14JuPEdqZG3AWmagiPAP.jpg', 2, 'A Quiet Place: Day One', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (12, 1184918, '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg', 5, 'The Wild Robot', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (13, 912649, '/8mRrl8lc7TrbdA1PFzUhQ0nFZ7R.jpg', 3, 'Venom: The Last Dance', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (14, 845781, '/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg', 3, 'Red One', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (15, 299536, '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', 5, 'Avengers: Infinity War', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (16, 1726, '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg', 5, 'Iron Man', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (17, 807, '/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg', 5, 'Se7en', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (18, 877817, '/vOX1Zng472PC2KnS0B9nRfM8aaZ.jpg', 3, 'Wolfs', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (19, 299534, '/or06FN3Dka5tukK1e9sl16pB3iy.jpg', 5, 'Avengers: Endgame', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (20, 976734, '/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg', 3, 'Canary Black', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (22, 1241982, '/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg', 4, 'Moana 2', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (23, 539972, '/i47IUSsN126K11JUzqQIOi1Mg1M.jpg', 3, 'Kraven the Hunter', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (24, 866398, '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg', 3, 'The Beekeeper', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (29, 950396, '/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg', 4, 'The Gorge', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (30, 307081, '/kSQ49Fi3NVTqGGXILmxV2T2pdkG.jpg', 4, 'Southpaw', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (35, 911430, '/vqBmyAj0Xm9LnS1xe1MSlMAJyHq.jpg', NULL, 'F1 The Movie', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (36, 617126, '/x26MtUlwtWD26d0G0FXcppxCJio.jpg', NULL, 'The Fantastic Four: First Steps', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (37, 541671, '/mKp4euM5Cv3m2U1Vmby3OGwcD5y.jpg', NULL, 'Ballerina', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (38, 1011477, '/c90Lt7OQGsOmhv6x4JoFdoHzw5l.jpg', NULL, 'Karate Kid: Legends', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (39, 547016, '/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg', NULL, 'The Old Guard', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (40, 846422, '/qjVMsjV7UmSpi1aHA9Wtl1v8cxr.jpg', NULL, 'The Old Guard 2', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (41, 1061474, '/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg', NULL, 'Superman', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (43, 1242898, '/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg', NULL, 'Predator: Badlands', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (42, 1376434, '/2XDQa6EmFHSA37j1t0w88vpWqj9.jpg', 3, 'Predator: Killer of Killers', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (4, 822119, '/jmobYdUXrbj1g5QFWjeomOk2Noz.jpg', 4, 'Captain America: Brave New World', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (50, 950387, '/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg', 3, 'A Minecraft Movie', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (51, 604079, '/wobVTa99eW0ht6c1rNNzLkazPtR.jpg', NULL, 'The Long Walk', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (52, 1078605, '/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg', NULL, 'Weapons', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (53, 533533, '/lyq8uQzxWTCIxWEKuxyQPrbVu40.jpg', NULL, 'TRON: Ares', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (54, 1062722, '/2ixPMFWyKtQ9C4ROo9xA12ci2yU.jpg', NULL, 'Frankenstein', 'panosdim@gmail.com', NULL);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (55, 1087891, '/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg', 4, 'The Amateur', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (27, 986056, '/jrlCcyFJek3BWnZhpU6MHtTMoDK.jpg', 4, 'Thunderbolts*', 'panosdim@gmail.com', true);
INSERT INTO movie (id, movie_id, poster, rating, title, user_id, watched) VALUES (56, 425274, '/oD3Eey4e4Z259XLm3eD3WGcoJAh.jpg', NULL, 'Now You See Me: Now You Don''t', 'panosdim@gmail.com', NULL);
