name: Build Multi-Architecture Native Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build native image for amd64
        run: ./gradlew bootBuildImage --imagePlatform=linux/amd64 --imageName=ghcr.io/${{ github.repository }}:amd64
      - name: Push amd64 image
        run: docker push ghcr.io/${{ github.repository }}:amd64 

  build-arm64:
    runs-on: [self-hosted, arm64]   # your self-hosted ARM64 runner label
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ARM64 native image inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          ghcr.io/graalvm/graalvm-ce:22.3.1 \
          ./gradlew bootBuildImage --imagePlatform=linux/arm64 --imageName=ghcr.io/${{ github.repository }}:arm64
      - name: Push arm64 image
        run: docker push ghcr.io/${{ github.repository }}:arm64 

  push-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create multi-arch manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository }}:latest \
            --amend ghcr.io/${{ github.repository }}:amd64 \
            --amend ghcr.io/${{ github.repository }}:arm64
      - name: Push multi-arch manifest
        run: docker manifest push ghcr.io/${{ github.repository }}:latest
