name: Build Multi-Architecture Native Image

on:
  push:
    branches:
      - main

jobs:
  build-native-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image for ${{ matrix.arch }}
        run: ./gradlew bootBuildImage --imagePlatform=linux/${{ matrix.arch }} --imageName=ghcr.io/${{ github.repository_owner }}/movies-track-api:${{ matrix.arch }}
      
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/movies-track-api:${{ matrix.arch }}
      
      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ghcr.io/${{ github.repository_owner }}/movies-track-api:latest \
            --amend ghcr.io/${{ github.repository_owner }}/movies-track-api:amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/movies-track-api:arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/movies-track-api:latest
